"""Initial_dev

Revision ID: 34557aeab2d1
Revises: 
Create Date: 2026-02-27 20:15:46.438073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34557aeab2d1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS system_settings CASCADE")
    op.execute("DROP INDEX IF EXISTS ix_worklog_categories_name CASCADE")
    op.execute("DROP TABLE IF EXISTS worklog_categories CASCADE")
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worklog_categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('worklog_categories_pkey'))
    )
    with op.batch_alter_table('worklog_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_worklog_categories_name'), ['name'], unique=True)

    op.create_table('system_settings',
    sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('system_settings_pkey'))
    )
    # ### end Alembic commands ###