"""add_org_units_to_user

Revision ID: 59a079ff4d1e
Revises: 836d72c4eb9e
Create Date: 2026-03-16 20:33:39.905686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59a079ff4d1e'
down_revision: Union[str, None] = '836d72c4eb9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###