"""add needs_password_change to users

Revision ID: af70a42aa7dc
Revises: 3a4a1dc3e5f7
Create Date: 2026-03-01 17:33:54.355181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af70a42aa7dc'
down_revision: Union[str, None] = '3a4a1dc3e5f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('needs_password_change', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('needs_password_change')
    # ### end Alembic commands ###
