"""Move_resource_fields_to_jira_user

Revision ID: ee8745040552
Revises: 34557aeab2d1
Create Date: 2026-02-27 20:56:36.243316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee8745040552'
down_revision: Union[str, None] = '34557aeab2d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jira_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weekly_quota', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_jira_users_is_active'), ['is_active'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_team_id_fkey'), type_='foreignkey')
        batch_op.drop_column('weekly_quota')
        batch_op.drop_column('team_id')

    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('weekly_quota', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('users_team_id_fkey'), 'teams', ['team_id'], ['id'])

    with op.batch_alter_table('jira_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jira_users_is_active'))
        batch_op.drop_column('weekly_quota')

    # ### end Alembic commands ###